### ISSUE TITLE
Files in \reactlient\assets

### ISSUE THREAD

**Issue by kromosomX** [hawkeye-stan/msfs-touch-panel#2]
Hi Stan, 
first of all I want to say that this is a great project. I'll be testing it in the next few days and I'll report each bug I find as a separate issue. 

The first one is that the release zip file contains files that it probably shouldn't in \reactclient\assets there are directories (g1000nxi, fbwa32nx, cj4, asobo) that are full of files. I deleted the files and the symlinks were created OK.

Regards, 
Tomaž

**Comment by hawkeye-stan** [comment]
Release has been repackaged with the files removed.

**Comment by kromosomX** [comment]
Thank you. Please check your e-mail ASAP!
