### ISSUE TITLE
PFD - G1000 (experimental 2) - missing colors for the sky and ground

### ISSUE THREAD

**Issue by kromosomX** [hawkeye-stan/msfs-touch-panel#6]
This may not be inplemented yet, but in your pictures the sky is blue and the ground is brown. With me both are black.

**Comment by hawkeye-stan** [comment]
Limitation of not able to render Bing Map in the app currently. To have sky and ground color, the PFD background has to set to non-map terrain render in PFD. With the buttons at the bottom of PFD bezel, please set 

PFD Opt => SVT => Terrain (uncheck)

**Comment by kromosomX** [comment]
Thank you. That did the trick. You better add this to the documentation.
