### ISSUE TITLE
MFD - G100 (Experimental 2) - connection issues

### ISSUE THREAD

**Issue by kromosomX** [hawkeye-stan/msfs-touch-panel#7]
I can connect to MFD from a local browser (Edge) and it works OK.

If I start the MFD from the Panels menu in the server it starts up and the bezel works OK, but the screen is blank.  Also if i try to start it without the bezel the screen is blank.

Also I can't get it to work from Ipad/Iphone - same issue as with the PFD.

**Comment by hawkeye-stan** [comment]
Try to close all instances of PFD/MFD across various platforms. The coherent debugger webservices only allow one instance of each view (PFD, MFD, etc) to be opened at a time. For example, if MFD panel is opened in Edge browser, no other platform can have the same panel open.

**Comment by kromosomX** [comment]
I am sure that I closed all the other instances before. I even restarted the computer. But now it works if it is started from the server. (not yet from the iPad)
I noticed that the PFD is MUCH more responsive if it is started from the server than if I connect to it from the Edge. I disabled some extensions and it working better but not as fast as from the server.
